apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw-oms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gw-oms
  template:
    metadata:
      labels:
        app: gw-oms
    spec:
      containers:
        - name: gw-oms
          image: rinsler/gw-oms:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: gw-oms
spec:
  type: ClusterIP
  selector:
    app: gw-oms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
